# Next Line is add to end on Dockerfile in container dev

# Install Kubectl
RUN sudo apt-get update
RUN sudo apt-get install -y ca-certificates curl
RUN sudo mkdir /etc/apt/keyrings/
RUN sudo touch /etc/apt/keyrings/kubernetes-archive-keyring.gpg
RUN sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
RUN sudo apt-get update
RUN sudo apt-get install -y kubectl