# Next Line is add to end on Kubectl in container dev

# Install Kubectl
RUN sudo apt-get update
RUN sudo apt-get install -y ca-certificates curl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert"
RUN sudo install -o root -g root -m 0755 kubectl-convert /usr/local/bin/kubectl-convert