# Next Line is add to angular, typescript and node

# Angular
RUN su node -c "npm install -g @angular/cli@12.2.1"

# TS
RUN su node -c "npm install -g typescript@4.4.2"

# Terraform
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
RUN sudo apt update && sudo apt install terraform=1.3.9